<a href="https://colab.research.google.com/github/arikaran007/python/blob/main/Numpy/Numpy_Springboard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A python List can be used to store a group of elements together in a sequence. It can contain heterogeneous elements.

In [1]:
item_list=['bread','milk','egg','butter']
mark=[43,76,98,45]
hetero_list=[1,2,3.0,"text",True,3+2j]

In [3]:
for i in range(len(mark)):
  mark[i]+=5
print(mark)

[48, 81, 103, 50]


In [12]:
%%time

list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
list3=[]

for i in range(len(list1)):
  list3.append(list1[i]+list2[i])
print(list3)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [11]:
%%time
import numpy as np

list1 = np.arange(1,1000000)
list2 = np.arange(2,1000001)

list3 = list1+list2

CPU times: user 7.4 ms, sys: 2.83 ms, total: 10.2 ms
Wall time: 18.3 ms


In [13]:
import numpy as np
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr


array([78, 92, 36, 64, 89])

Multiple array

In [14]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr


array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [15]:
car_attributes_arr.shape

(3, 5)

In [18]:
car_attributes_arr.dtype

dtype('int64')

 Accessing element from 1D array.

In [19]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1]

'buick skylark 320'

 Accessing elements from a 2D array

In [20]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]

car_power = np.array([car_names,horsepower])
car_power

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [21]:
car_power[1]

array(['130', '165', '150', '150', '140'], dtype='<U25')

In [22]:
car_power[0,2]

'plymouth satellite'

Slicing from 1D array

In [25]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
car_names[1:3]

['buick skylark 320', 'plymouth satellite']

Slicing from a 2D array

In [26]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
total = np.array([car_names,horsepower,acceleration])
total


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U25')

In [27]:
horsepower = [130, 165, 150, 150, 140]
car = np.array(horsepower)
np.mean(car)

147.0

In [28]:
np.median(car)

150.0

In [31]:
 print(np.min(car))
 print(np.max(car))

130
165


Index of minimum and maximum values:

In [32]:
np.argmax(car)

1

In [33]:
np.argmin(car)

0

The engineers at XYZ Custom Cars want to know the horsepower of cars that are greater than or equal to 150.

In [35]:
x = np.where(car >= 150)
print(x)

car[x]

(array([1, 2, 3]),)


array([165, 150, 150])

The Engineers at XYZ Custom Cars want to create a separate array consisting of filtered values of horsepower greater than 135.

In [36]:
filt = car > 135
new = car[filt]

print(new)

[165 150 150 140]


The engineers at XYZ Custom Cars want the horsepower in sorted order.

In [39]:
sort_new=np.sort(car)
print(sort_new)

[130 140 150 150 165]


Numpy provides various mathematical functions such as sum(), add(), sub(), log(), sin() etc. which uses vectorization.

In [40]:
student_marks_arr = np.array([78, 92, 36, 64, 89])
print(np.sum(student_marks_arr))

359


In [42]:

np.arange(0,10000)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Linspace:

This method returns the given number of evenly spaced values, between the given intervals. By default, the number of values between a given interval is 50.

In [43]:
arr = np.linspace(1,10)
print(arr)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [45]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [46]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.ones(2)

array([1., 1.])

In [48]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [50]:
np.full([3,3],"ari")

array([['ari', 'ari', 'ari'],
       ['ari', 'ari', 'ari'],
       ['ari', 'ari', 'ari']], dtype='<U3')

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.random.rand(22)

array([0.88904951, 0.69608665, 0.2440969 , 0.89592435, 0.21316952,
       0.40499018, 0.08064272, 0.52381682, 0.19909348, 0.45069307,
       0.39987458, 0.11304795, 0.87997064, 0.20361444, 0.03316118,
       0.90924652, 0.66387723, 0.93321002, 0.83647477, 0.66368773,
       0.00138794, 0.38431089])

In [54]:
np.random.randint(1,10, size=3)

array([1, 9, 7])

In [56]:
x = np.random.choice([9, 3, 7, 5])
print(x)


5
